### ISSUE TITLE
3D Style Sheet

### ISSUE THREAD

**Issue by MurkoBoi** [conkolas/client-project#16]
![Bo-stylesheet](https://user-images.githubusercontent.com/32542036/64407803-8a3d1f00-d085-11e9-977a-939f6d49d9e8.jpg)

**Comment by conkolas** [comment]
![Stylesheet](https://user-images.githubusercontent.com/5579599/64355178-0a6d7100-d001-11e9-8f95-353526aa0450.jpg)
