### ISSUE TITLE
Concept art

### ISSUE THREAD

**Issue by conkolas** [conkolas/client-project#6]

**Comment by bohamer** [comment]
![WhatsApp Image 2019-09-05 at 19 54 09](https://user-images.githubusercontent.com/54839709/64367158-ef5a2b80-d017-11e9-942b-f2166dd49618.jpeg)
![WhatsApp Image 2019-09-05 at 19 54 09 (1)](https://user-images.githubusercontent.com/54839709/64367159-ef5a2b80-d017-11e9-8ec6-58e0b1296599.jpeg)
